name: Style Check
on:
  push:
    branches: [main]
jobs:
  style_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.13.1"

      - name: Install Dependancies
        run: npm install

      - name: Build Project (includes type check)
        run: npm run build

      - name: Run eslint
        if: ${{ success() }}
        run: npm run lint

      - name: Run prettier
        if: ${{ success() }}
        run: npm run format
